# -*- coding: utf-8 -*-
"""1_amonsap_t01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRBk9WOCD8uYr4hxrF5ZhGWPjtVYrv5B
"""

import pandas as pd

data = '/content/DataEngineering/fcc-new-coder-survey.xlsx'

data_col = ['Age', 'AttendedBootcamp', 'CountryCitizen', 'Gender', 'MonthsProgramming']

sheet2016 = pd.read_excel(data, sheet_name='2016', header=2, usecols=data_col)
sheet2017 = pd.read_excel(data, sheet_name='2017', header=2, usecols=data_col)

sheet2016['Year'] = 2016
sheet2017['Year'] = 2017

dataframe = pd.concat([sheet2016, sheet2017], axis=0, ignore_index=True)

dataframe.dropna(axis=0, inplace=True)

print(dataframe)

tmp = dataframe.groupby('CountryCitizen')['MonthsProgramming'].agg(sum=('sum'), max=('max'), min=('min'),avg=('mean'))

print(tmp.head(5))

tmp.to_excel('/content/DataEngineering/conclude.xlsx')

